name: CF Tunnel

on:
  push:
    paths:
      - '.github/workflows/cf.yml'
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Install cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

      - name: Run tunnel
        run: |
          cloudflared tunnel run --token eyJhIjoiMGQ1MTNmYjQ2ZWJkODc2NTA3MTZhMGQ3Yzk1MjUwMjQiLCJ0IjoiZDU1MjgxYjAtNjk0NC00MjdiLWExNDAtOGUxYTEzZDc5YzljIiwicyI6Ik1qQTRPVEk0WVRrdE9EQTJNaTAwTTJZd0xXRXlaVEF0TVRoaE9Ea3dNRE5oTlRGbCJ9
