tunnel: <你的 tunnel id>
credentials-file: /root/.cloudflared/<你的 tunnel id>.json

ingress:
  - hostname: ""
    service: ssh://localhost:22
  - service: http://localhost:8080

originRequest:
  noTLSVerify: true
  proxyProtocol: false

args:
  - --protocol
  - tcp
  - --proxy-password
  - freevpn123
