name: cf-tunnel

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Download cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Run tunnel
        run: |
          echo "${{ secrets.CLOUDFLARED_TOKEN }}" > tunnel.json
          nohup cloudflared tunnel run --config tunnel.json > output.log 2>&1 &
          sleep 30
